/* eslint-disable */
// THIS FILE IS GENERATED BY scripts/generate-ts-types.mjs
// DO NOT EDIT BY HAND. Run `pnpm types:gen` after any schema change.
//
// Source of truth: tools/fandomforge/schemas/*.schema.json
// Generated at: 2026-04-20T04:23:28.395Z


export type Layer = {
    name: string;
    role: "music" | "dialogue" | "sfx" | "ambient" | "riser" | "impact" | "foley" | "voiceover";
    gain_db: number;
    file?: string;
    pan?: number;
    eq_preset?: string;
    reverb_preset?: string;
  };

export type DuckEvent = {
    from_sec: number;
    to_sec: number;
    target_layer: string;
    duck_db: number;
    attack_ms?: number;
    release_ms?: number;
  };

/** Full audio mix plan: layers, per-layer gain, ducking curves, SFX impacts, loudness targets. Produced by audio-producer, consumed by QA gate and NLE exporters. */
export interface AudioPlan {
    schema_version: 1;
    project_slug: string;
    target_lufs: number;
    true_peak_ceiling_dbtp: number;
    song_gain_db?: number;
    layers: Array<Layer>;
    duck_events?: Array<DuckEvent>;
    /** SFX impacts synced to drops/downbeats. */
    impacts?: Array<{
    at_sec: number;
    kind: "impact" | "riser" | "whoosh" | "sub_boom" | "tail" | "reverse_cymbal";
    gain_db?: number;
    file?: string;
  }>;
    generated_at?: string;
    generator?: string;
  }

/** Full beat analysis for a single audio file. Produced by `ff beat analyze` and consumed by every downstream pipeline stage. */
export interface BeatMap {
    /** Schema version. Currently 1. */
    schema_version?: 1;
    song: string;
    artist: string;
    duration_sec: number;
    bpm: number;
    bpm_confidence: number;
    /** Time signature as 'N/M' e.g. '4/4', '3/4', '6/8'. */
    time_signature: string;
    beats: Array<number>;
    downbeats: Array<number>;
    onsets: Array<number>;
    /** Detected musical key (e.g. 'C#m', 'Fmaj'). Optional — set only when madmom or essentia is available. */
    key?: string;
    /** Which detector produced the downbeats. 'madmom-dbn' is preferred; 'librosa-heuristic' is the fallback approximation. */
    downbeat_source?: "madmom-dbn" | "madmom-rnn" | "librosa-heuristic";
    drops?: Array<{
    time: number;
    intensity: number;
    type: string;
  }>;
    buildups?: Array<{
    start: number;
    end: number;
    curve: "linear" | "exponential" | "stepped";
  }>;
    breakdowns?: Array<{
    start: number;
    end: number;
    intensity: number;
  }>;
    /** Per-sample normalized energy. Each entry is [time_sec, energy_0_to_1]. */
    energy_curve?: Array<Array<unknown>>;
    generated_at?: string;
    /** Tool/version tag that produced this artifact. */
    generator?: string;
  }

export type Clip = {
    id: string;
    source_title: string;
    source_type: "movie" | "tv" | "anime" | "game" | "other";
    fandom: string;
    timestamp: string;
    duration_sec: number;
    description: string;
    mood_tags?: Array<string>;
    framing?: "" | "ECU" | "CU" | "MCU" | "medium" | "MS" | "MWS" | "wide" | "WS" | "EWS" | "insert" | "OTS" | "POV";
    motion?: string;
    color_notes?: string;
    notes?: string;
    created_at?: string;
    /** Optional stable source identifier (blake3 hash or CAS key). */
    source_id?: string;
    /** Optional list of character names confidently detected in the shot. */
    characters?: Array<string>;
    scene_number?: number;
  };

/** File-backed clip catalog produced by fandomforge.catalog.Catalog.save(). */
export interface Catalog {
    version: 1;
    updated_at: string;
    clips: Array<Clip>;
  }

/** Formal taxonomy of clip categories, shared across the engine. Locked here so multiple modules (energy-zone mapping, slot-fit scoring, type-specific weighting, QA rules) all key off the same vocabulary instead of inventing their own. Reference this schema's enum from any module that classifies a shot's purpose. */
export interface ClipCategory {
    schema_version: 1;
    /** The full enumerated taxonomy. Order is the canonical ordering for documentation and UI surfaces. */
    categories: Array<{
    id: "establishing" | "action-high" | "action-mid" | "reaction-quiet" | "reaction-emotional" | "dialogue-primary" | "dialogue-reaction" | "transitional" | "climactic" | "resolution" | "texture";
    label: string;
    description: string;
    /** Which energy zones this category fits naturally. From energy-zones.schema.json zone labels. */
    energy_zone_affinity: Array<"low" | "mid" | "high" | "drop" | "buildup" | "breakdown">;
    /** Per edit-type weight multiplier (1.0 = neutral). Slot-fit scorer multiplies a candidate's category-fit score by this for the active edit type. */
    edit_type_bias?: {
    action?: number;
    emotional?: number;
    tribute?: number;
    shipping?: number;
    speed_amv?: number;
    cinematic?: number;
    comedy?: number;
    hype_trailer?: number;
    dialogue_narrative?: number;
    dance_movement?: number;
    sad_emotional?: number;
  };
  }>;
  }

/** One node in a DaVinci-style color tree. Floats are in their natural ranges (exposure in stops, saturation 0..2, etc). */
export type ColorNode = {
    label?: string;
    exposure_stops?: number;
    contrast?: number;
    saturation?: number;
    temperature_k?: number;
    tint?: number;
    lift?: {
    r?: number;
    g?: number;
    b?: number;
    y?: number;
  };
    gamma?: {
    r?: number;
    g?: number;
    b?: number;
    y?: number;
  };
    gain?: {
    r?: number;
    g?: number;
    b?: number;
    y?: number;
  };
    /** Hue-vs-saturation adjustments in 6 buckets (red, yellow, green, cyan, blue, magenta). Values in [0, 2]. */
    hue_vs_sat?: {
    red?: number;
    yellow?: number;
    green?: number;
    cyan?: number;
    blue?: number;
    magenta?: number;
  };
    /** HSL qualifier for targeted adjustments (e.g. skin tones). */
    qualifier?: {
    hue_center?: number;
    hue_width?: number;
    sat_min?: number;
    sat_max?: number;
  };
  };

/** Per-project color unification plan. Specifies the hero frame, global LUT, and per-source adjustments. */
export interface ColorPlan {
    schema_version: 1;
    project_slug: string;
    target_color_space: "Rec.709" | "Rec.2020" | "DCI-P3" | "sRGB" | "ACEScg";
    /** Path to a .cube LUT applied at the global timeline level. */
    global_lut?: string;
    global_lut_intensity?: number;
    /** Reference frame used for histogram matching. */
    hero_frame?: {
    source_id: string;
    timecode: string;
    image_path?: string;
  };
    /** Per-source grade adjustments. Keyed by source_id. */
    per_source: Record<string, {
    lut?: string;
    lut_intensity?: number;
    nodes: Array<ColorNode>;
  }>;
    /** Rare per-shot overrides (keyed by shot.id) when a shot needs a custom grade. */
    per_shot_overrides?: Record<string, Array<ColorNode>>;
    generated_at?: string;
    generator?: string;
  }

/** Cross-source action complement pairs. When a shot shows an action being thrown (punch, kick, shot fired), this plan pairs it with a shot from a DIFFERENT source showing the action being received. Produced by `ff sync complement`; consumed by the renderer to place cause→effect cuts on adjacent beats. */
export interface ComplementPlan {
    schema_version: 1;
    project_slug: string;
    pairs: Array<{
    thrown_shot_id: string;
    received_shot_id: string;
    kind: "punch" | "kick" | "gunshot" | "blade" | "tackle" | "block";
    score: number;
    reasons?: Array<string>;
  }>;
    /** Thrown-action shots with no suitable complement found. */
    unpaired_thrown?: Array<string>;
    /** Received-action shots that weren't used as a complement. */
    unpaired_received?: Array<string>;
    generated_at?: string;
    generator?: string;
  }

/** Resolved placement decisions for a list of dialogue cues against the dialogue-windows analysis. Each cue gets PLACE / SHIFT / REJECT with a reason; the mixer reads this to know where to actually drop each cue's audio. */
export interface DialoguePlacementPlan {
    schema_version: 1;
    project_slug?: string;
    placements: Array<{
    cue_index: number;
    requested_start_sec: number;
    cue_duration_sec: number;
    placed_start_sec: number;
    decision: "PLACE" | "SHIFT" | "REJECT";
    flag_at_placement: "SAFE" | "RISKY" | "BLOCKED";
    reason: string;
    suggested_alternative_sec?: number | null;
  }>;
    summary: {
    place: number;
    shift: number;
    reject: number;
  };
    generator?: string;
  }

/** Per-time classification of where injected dialogue can land cleanly. Derived from energy-zones + beat-map. Each window slice is flagged SAFE / RISKY / BLOCKED with explicit reason codes so the editor can see WHY a placement was approved or refused. */
export interface DialogueWindows {
    schema_version: 1;
    duration_sec: number;
    resolution_sec: number;
    safe_window_count: number;
    risky_window_count: number;
    blocked_window_count: number;
    windows: Array<{
    start_sec: number;
    end_sec: number;
    flag: "SAFE" | "RISKY" | "BLOCKED";
    reason_codes: Array<string>;
    min_duration_available_sec?: number;
    rms_at_start?: number;
    mid_density_at_start?: number;
  }>;
    generator?: string;
  }

export type Act = {
    number: number;
    name: string;
    start_sec: number;
    end_sec: number;
    energy_target: number;
    emotional_goal: string;
    /** Target shot-cadence band for this act. slow = breathing room (2-4s shots), medium = standard (1-2s), fast = quick (0.4-1s), frantic = drop-tier (sub-0.5s). Used by slot-fit + shot proposer to set duration budgets per act so the edit breathes through low-energy zones and hits hard during drops. */
    pacing?: "slow" | "medium" | "fast" | "frantic";
    /** Target tension contribution of this act, -1 (full release) to +1 (peak tension). Read by the tension-curve constructor and the arc-shape evaluator to verify the rendered edit climbs and resolves as planned. */
    tension_target?: number;
    /** Role of this act in the overall narrative arc. Cross-type: every edit type has a setup, an escalation, a climax, and a release — even comedy. Length and order can vary; role names are fixed. */
    arc_role?: "setup" | "escalation" | "climax" | "release" | "interlude";
    fandom_focus?: Record<string, number>;
    /** References to beat-map events this act should align to (e.g. 'main_drop', 'downbeat:32'). */
    beat_targets?: Array<string>;
    key_image?: string;
    avoid?: Array<string>;
    learning?: string;
    /** Optional intentional-reuse markers for this act. Each entry names a planned shot id and (for callbacks) the id of the earlier shot it repeats. The proposer honors these by reusing the referenced source + timecode. */
    shot_intents?: Array<ShotIntent>;
  };

export type ShotIntent = {
    id: string;
    intent: "callback" | "motif" | "rhyme";
    callback_of?: string;
    note?: string;
  };

export type HandoffRef = {
    path: string;
    status: "pending" | "draft" | "final" | "approved";
    validated_at?: string;
    schema_id?: string;
  };

/** Master edit plan — the concept, song, fandoms, act breakdown, and explicit handoff refs to every downstream artifact. Produced by edit-strategist, referenced by every other agent. */
export interface EditPlan {
    schema_version: 1;
    project_slug: string;
    concept: {
    theme: string;
    one_sentence: string;
    mode?: "convergent" | "parallel" | "relay" | "woven" | "single-character";
    archetype?: string;
    risks?: Array<string>;
  };
    song: {
    title: string;
    artist: string;
    file?: string;
    duration_sec?: number;
    credit_line?: string;
  };
    fandoms: Array<{
    name: string;
    share?: number;
    primary_characters?: Array<string>;
  }>;
    vibe: "action" | "emotional" | "hype" | "sad" | "funny" | "mixed" | "cinematic" | "horror" | "romantic" | "triumphant";
    length_seconds: number;
    platform_target: "youtube" | "tiktok" | "reels" | "shorts" | "twitter" | "master";
    resolution?: {
    width: number;
    height: number;
  };
    fps?: number;
    target_lufs?: number;
    acts: Array<Act>;
    /** Planned per-act or per-second energy target (0-100). Used by QA to compare against actual beat-map energy curve. */
    energy_curve?: Array<Array<unknown>>;
    /** Required downstream artifacts. Each entry is validated before the edit is considered 'done planning'. */
    handoffs?: {
    beat_map?: HandoffRef;
    shot_list?: HandoffRef;
    color_plan?: HandoffRef;
    transition_plan?: HandoffRef;
    audio_plan?: HandoffRef;
    title_plan?: HandoffRef;
  };
    credits?: {
    song_credit?: string;
    source_credits?: Array<string>;
    fair_use_statement?: string;
  };
    copyright_overrides?: Array<{
    rule: string;
    reason: string;
  }>;
    generated_at?: string;
    generator?: string;
    /** Top-level intentional-reuse markers that apply across the whole edit (bookends, motifs). Use this when a callback spans two different acts. */
    shot_intents?: Array<ShotIntent>;
  }

export type Sample = {
    shot_id: string;
    time_sec: number;
    /** Aligned to parent `dimensions`. Each value in [0, 1]. */
    vector: Array<number>;
    intensity: number;
    dominant?: string;
    confidence?: number;
  };

/** Per-shot emotion vector and scalar intensity across the edit, used to flag emotional dead zones and sync peaks to drops. */
export interface EmotionArc {
    schema_version: 1;
    project_slug: string;
    /** Ordered list of emotion labels. Each sample's vector is aligned to this order. */
    dimensions: Array<string>;
    samples: Array<Sample>;
    method?: "heuristic_v1" | "clip_prompts_v1" | "transcript_sentiment_v1" | "mixed_v1";
    generated_at?: string;
    generator?: string;
  }

/** Per-time energy classification of a song. Splits the track into labeled structural zones (low/mid/high/drop/buildup/breakdown), provides per-band (bass/mid/treble) energy at fixed resolution, and types each detected onset as percussive vs sustained. Foundation for pacing logic and dialogue-window detection. */
export interface EnergyZones {
    schema_version: 1;
    duration_sec: number;
    sample_rate_hz: number;
    /** Time resolution of the bands array and zone boundary precision. 0.25s default = 4 samples/sec. */
    resolution_sec: number;
    /** Contiguous regions of similar energy character. Sorted by start_sec. */
    zones: Array<{
    start_sec: number;
    end_sec: number;
    label: "low" | "mid" | "high" | "drop" | "buildup" | "breakdown";
    confidence: number;
    avg_energy: number;
  }>;
    /** Per-band normalized energy at fixed time resolution. Each band is normalized to its own peak so cross-band comparisons reflect relative dominance, not absolute loudness. */
    bands: Array<{
    time_sec: number;
    bass: number;
    mid: number;
    treble: number;
  }>;
    /** Detected onsets with type label. Percussive onsets are sharp transients suitable for cuts; sustained onsets are tonal swells where cutting feels off-beat. */
    transients: Array<{
    time_sec: number;
    amplitude: number;
    kind: "percussive" | "sustained";
    flatness: number;
  }>;
    generator?: string;
  }

export type Fandom = {
    name: string;
    /** Alternate names or abbreviations users might type. */
    aliases?: Array<string>;
    medium?: "film" | "tv" | "anime" | "game" | "comic" | "book" | "other";
    seasons?: Array<number>;
    /** Short note on the color grade, framing, and palette of this property. Guides color-grader. */
    visual_language?: string;
    /** Songs strongly associated with this fandom (trailers, opening themes, iconic needle drops). */
    canonical_songs?: Array<string>;
    iconic_scenes?: Array<Scene>;
    notes?: string;
  };

export type Scene = {
    /** Short human-readable description of the moment. */
    scene: string;
    episode?: string;
    film?: string;
    /** Timestamp in H:MM:SS or MM:SS form. */
    timestamp?: string;
    duration_sec?: number;
    /** Primary emotion the scene carries (grief, triumph, fear, etc.). */
    emotion?: string;
    tags?: Array<string>;
    /** Moments in the scene that match common beat-map events. */
    sync_targets?: Array<"drop" | "buildup" | "breakdown" | "downbeat" | "vocal-hook">;
  };

/** Per-project user-extensible fandom knowledge. Lives at projects/<slug>/fandoms.json and is loaded into expert chat context so fandom-researcher and others have access to your custom scenes, visual language notes, and song suggestions alongside their built-in prose knowledge. */
export interface Fandoms {
    schema_version: 1;
    fandoms: Array<Fandom>;
  }

/** First-pass interpretation of a user prompt into structured edit intent. Drives every downstream stage: edit_type picks priors, tone_vector picks template + color, speakers seed dialogue search, target_duration_sec drives arc-length math. Produced before any audio analysis or ingest, so the rest of the pipeline can plan around it. */
export interface Intent {
    schema_version: 1;
    /** The original prompt the user supplied. Stored verbatim for re-classification when the classifier is updated. */
    prompt_text: string;
    /** Resolved edit type from the existing 8-type taxonomy plus the new dialogue_narrative + dance_movement + sad_emotional types added in v2. */
    edit_type: "action" | "emotional" | "tribute" | "shipping" | "speed_amv" | "cinematic" | "comedy" | "hype_trailer" | "dialogue_narrative" | "dance_movement" | "sad_emotional";
    /** Where the edit_type came from. */
    edit_type_source?: "explicit" | "classified" | "default";
    /** 8-dim emotional tone target. Order: [grief, triumph, fear, awe, tension, release, sorrow, elation]. Each 0-1. */
    tone_vector: Array<number>;
    /** Named characters / speakers referenced in the prompt or implied by the source list. Used by the dialogue-narrative pipeline to seed dialogue search. */
    speakers: Array<{
    name: string;
    role?: "protagonist" | "antagonist" | "narrator" | "supporting" | "ensemble" | "unknown";
    fandom?: string;
    /** Short note on how this speaker was inferred (prompt mention / source filename / fandom roster). */
    evidence?: string;
  }>;
    /** Recommended template id (matches one of edit-types.json templates) or 'custom' if no preset matches well. */
    auto_template: "action" | "emotional" | "tribute" | "shipping" | "speed_amv" | "cinematic" | "comedy" | "hype_trailer" | "dialogue_narrative" | "dance_movement" | "sad_emotional" | "custom";
    /** How long the final edit should run. Parsed from prompt ('30 seconds', 'full song', '2 minutes') or defaults to the song duration. */
    target_duration_sec: number;
    /** Where the target duration came from. */
    duration_source?: "prompt" | "song" | "default";
    /** Fandom families involved (anime, marvel, mcu, etc.). Used for fandom-balance + per-bucket prior selection. */
    fandoms?: Array<string>;
    /** Overall classifier confidence. Below 0.5 → engine should ask the user to confirm. */
    confidence: number;
    /** True if confidence is low enough that the engine should pause and confirm with the user before proceeding. */
    needs_user_confirmation?: boolean;
    generated_at?: string;
    generator?: string;
  }

/** Output of `ff review` and autopilot `post_render_review` step. Captures the five-dimension grading pass against a rendered edit (technical, visual, audio, structural, shot_list) with an overall letter grade and ship recommendation. */
export interface PostRenderReview {
    schema_version: 1;
    project_slug: string;
    video_path: string;
    generated_at: string;
    overall: "green" | "yellow" | "red";
    overall_verdict: "pass" | "warn" | "fail";
    /** Weighted 0-100 score across the five dimensions. */
    score: number;
    grade: "A+" | "A" | "A-" | "B+" | "B" | "B-" | "C+" | "C" | "C-" | "D+" | "D" | "D-" | "F";
    /** Human-readable guidance: ship / review with caveats / do not ship. */
    ship_recommendation: string;
    dimensions: Array<{
    name: "technical" | "visual" | "audio" | "structural" | "shot_list";
    verdict: "pass" | "warn" | "fail";
    score: number;
    findings?: Array<string>;
    /** Dimension-specific metrics (ffprobe output, loudness numbers, shot distribution, etc). */
    measurements?: Record<string, unknown>;
  }>;
  }

/** Per-project configuration. Lives at projects/<slug>/project-config.yaml (or .json). Every field has a default, so partial configs are valid. */
export interface ProjectConfig {
    schema_version?: 1;
    character?: string;
    character_aliases?: Array<string>;
    era_source_map?: Record<string, string>;
    excluded_sources?: Array<string>;
    narrative_priorities?: Array<string>;
    era_arc?: Array<{
    start: number;
    end: number;
    sources: Array<string>;
  }>;
    concept_beats?: Array<{
    time: number;
    duration: number;
    source: string;
    clip_start: number;
    desc?: string;
  }>;
    song?: string;
    song_offset_sec?: number;
    song_gain_db?: number;
    default_duck_db?: number;
    template?: string;
    vision_context?: string;
    add_titles?: boolean;
    apply_transitions?: boolean;
    add_sfx?: boolean;
    run_qa?: boolean;
    extract_missing_vo?: boolean;
    run_director?: boolean;
    build_storyboard?: boolean;
    build_thumbnail?: boolean;
    generate_captions?: boolean;
    build_youtube_meta?: boolean;
    copyright_audit?: boolean;
    enrich_motion?: boolean;
    enrich_gaze?: boolean;
    target_duration_sec?: number | null;
    export_presets?: Array<"youtube" | "tiktok" | "reels" | "shorts" | "twitter" | "master">;
    cluster_archetype?: string;
    lut_name?: string;
    lut_intensity?: number;
    /** Optional multifandom project descriptor — fandoms referenced by shots in this project. */
    fandoms?: Array<{
    name: string;
    share?: number;
    primary_characters?: Array<string>;
  }>;
    /** Primary delivery platform. Drives QA safe-area rules, export presets, loudness targets. */
    platform_target?: "youtube" | "tiktok" | "reels" | "shorts" | "twitter" | "master";
    target_loudness_lufs?: number;
    true_peak_ceiling_dbtp?: number;
    /** The category of edit this project is — drives type-specific priors (target pacing, sync style, transition bias, color palette). When absent, the sync planner auto-detects from the edit-plan prompt. See docs/edit-types/ for definitions. */
    edit_type?: "action" | "emotional" | "tribute" | "shipping" | "speed_amv" | "cinematic" | "comedy" | "hype_trailer";
  }

/** Per-render psychology proxy telemetry (Phase 5.1). Stored every render, NOT graded — when calibration data exists, future correlation work can connect these proxies to actual viewer reception. Fields are deliberately permissive (most optional) so the schema doesn't churn as the proxy methodology evolves. Read by `ff psych report <project>` (amendment A6 read-path commitment). */
export interface PsychologyReport {
    schema_version: 1;
    project_slug: string;
    video_path?: string;
    edit_type?: string;
    /** Each proxy block is independently optional so a partial render still produces a valid report. */
    proxies: {
    /** Character familiarity + viewer-bonding proxies. */
    parasocial?: {
    /** Per-character total seconds on screen across the edit. */
    character_screen_time_sec?: Record<string, number>;
    primary_character?: string;
    primary_character_share_pct?: number;
    /** Percent of shots where eyeline = camera (intimacy proxy). */
    eyeline_to_camera_pct?: number;
  };
    /** Music tempo vs viewer physiology proxy. */
    beat_entrainment?: {
    song_bpm?: number;
    heart_rate_band?: "resting" | "calm" | "active" | "hype" | "frantic" | "off-band";
    /** Percent of cuts within ±2 frames of a beat. */
    beat_sync_pct?: number;
  };
    /** Visual cohesion across mixed sources. */
    gestalt_unity?: {
    /** Percent of adjacent shots with luma delta < 0.15 (Gestalt grouping proxy). */
    color_grouping_pct?: number;
    /** Shannon entropy of fandom distribution, normalized 0-1. */
    fandom_diversity_idx?: number;
  };
    /** Per-fandom screen-time + canonical-arc adherence. */
    fandom_reception?: {
    fandom_screen_time_sec?: Record<string, number>;
  };
  };
    notes?: Array<string>;
    generated_at: string;
    generator?: string;
  }

/** Output of `ff qa gate` and `ff qa post-render`. Captures every rule checked, its result, and any override used. */
export interface QaReport {
    schema_version: 1;
    project_slug: string;
    stage: "pre-export" | "post-render";
    status: "pass" | "warn" | "fail";
    rules: Array<{
    id: string;
    name: string;
    level: "block" | "warn" | "info";
    status: "pass" | "warn" | "fail" | "skipped" | "overridden";
    message?: string;
    /** Concrete evidence for the ruling: file paths, timestamps, counts. */
    evidence?: Record<string, unknown>;
    override_reason?: string;
  }>;
    summary?: {
    total?: number;
    passed?: number;
    warned?: number;
    failed?: number;
    overridden?: number;
  };
    generated_at?: string;
    generator?: string;
  }

/** Aggregate editing statistics learned from a corpus of reference fandom videos. The sync planner reads these priors (when present) to bias shot duration, cuts-per-minute, and act pacing toward the patterns of real edits the user likes. */
export interface ReferencePriors {
    schema_version: 1;
    /** Free-form label for this corpus (e.g. 'john-wick-style', 'anime-speed-edits'). */
    tag?: string;
    source_playlists?: Array<string>;
    video_count: number;
    videos: Array<{
    id: string;
    title: string;
    url?: string;
    duration_sec: number;
    /** Optional YouTube-sourced metadata — view_count, like_count, like_ratio, channel, upload_date (YYYYMMDD), duration_sec, title. */
    youtube_metadata?: Record<string, unknown>;
    /** Composite 0-100 quality score combining audience reception + editing craft. */
    quality_score?: number;
    quality_tier?: "S" | "A" | "B" | "C" | "D";
    /** Per-axis scores that combine into quality_score. */
    quality_components?: Record<string, unknown>;
    /** Extensible metrics block. Deep analyzer adds pacing curve, visual stats, beat-sync rate, transitions distribution, motion-cut distribution, and lyric-alignment on top of the basic duration stats. */
    metrics: {
    shot_count?: number;
    avg_shot_duration_sec?: number;
    median_shot_duration_sec?: number;
    cuts_per_minute?: number;
    min_shot_duration_sec?: number;
    max_shot_duration_sec?: number;
    shot_duration_stddev_sec?: number;
    shot_duration_p25?: number;
    shot_duration_p75?: number;
    shot_duration_p90?: number;
    /** Cuts-per-minute over time (sliding window). */
    pacing_curve?: Array<{
    t_sec: number;
    cpm: number;
  }>;
    /** Percentage of shots in act 1 / 2 / 3 thirds. */
    act_pacing_pct?: Array<number>;
    intro_to_first_cut_sec?: number;
    outro_after_last_cut_sec?: number;
    sampled_shots?: number;
    avg_luma?: number;
    luma_stddev?: number;
    dark_shot_pct?: number;
    bright_shot_pct?: number;
    hue_median_deg?: number;
    saturation_mean?: number;
    motion_available?: boolean;
    motion_events?: number;
    beat_sync_available?: boolean;
    tempo_bpm?: number;
    cuts_on_beat_pct?: number;
    cuts_checked?: number;
  };
  }>;
    /** Corpus-wide editing signatures. Used by the sync planner to bias matches toward reference style. */
    priors: {
    median_shot_duration_sec: number;
    cuts_per_minute: number;
    /** Percentage of total shots that land in act 1 / 2 / 3. */
    typical_act_pacing_pct?: Array<number>;
    /** [p10, p90] shot duration range. */
    shot_duration_range_sec?: Array<number>;
    /** Average % of cuts that fall on the beat across the corpus. */
    cuts_on_beat_pct_mean?: number;
    /** Median tempo of the corpus's songs. */
    tempo_bpm_median?: number;
    /** Corpus-wide average luma — low = mostly dark edits, high = bright. */
    avg_luma_mean?: number;
    dark_shot_pct_mean?: number;
    bright_shot_pct_mean?: number;
    saturation_mean_mean?: number;
    intro_to_first_cut_sec_median?: number;
    /** Categorical pacing signature derived from the average pacing curve shape. */
    pacing_profile?: "slow-burn" | "steady" | "escalator" | "peaks-and-valleys" | "machine-gun";
  };
    generated_at?: string;
    generator?: string;
  }

/** Scene-cut detection output for a source video. Produced by PySceneDetect during ingest. */
export interface Scenes {
    schema_version: 1;
    source_id: string;
    detector: "content" | "adaptive" | "threshold" | "hash";
    threshold?: number;
    scenes: Array<{
    index: number;
    start_sec: number;
    end_sec: number;
    start_frame?: number;
    end_frame?: number;
    shot_type?: "" | "ECU" | "CU" | "MCU" | "medium" | "MS" | "MWS" | "wide" | "WS" | "EWS" | "insert" | "OTS" | "POV";
    motion_magnitude?: number;
    dominant_color_hex?: string;
    thumbnail_path?: string;
  }>;
    generated_at?: string;
  }

/** Action sound-effects plan. Describes where and how punchy impact / weapon / combat SFX should land in the final mix, beat-aligned with the song. Produced by `ff sfx plan` from the shot-list + beat-map and consumed by the mixer. */
export interface SfxPlan {
    schema_version: 1;
    project_slug: string;
    /** Controls whether original source-clip audio is blended under the song. */
    scene_audio_blend: {
    enabled: boolean;
    /** Gain applied to source-clip audio. Typical -18 to -24 dB so it sits under the song. */
    gain_db: number;
    /** Duck the scene audio by this much when the song peaks (drops). */
    duck_to_song_db?: number;
    /** Duck the scene audio by this much (additive on top of gain_db) while a dialogue cue is playing. Default -60 dB = effectively silent. Lets injected narrative dialogue sit clean on top of source ambient bleed. */
    duck_db_during_dialogue?: number;
  };
    /** Ordered list of SFX placements, each pointing at a variant pack. */
    events: Array<{
    id: string;
    time_sec: number;
    kind: "gunshot" | "gun_cock" | "punch" | "kick" | "impact" | "whoosh" | "sub_boom" | "riser" | "reverse_cymbal" | "glass_break" | "explosion" | "sword_clash";
    /** Which SFX file in the pack to use. Rotation is pre-picked so the same shot doesn't reuse the identical sound. */
    variant: string;
    gain_db?: number;
    source_shot_id?: string;
    beat_aligned?: boolean;
    reason?: string;
  }>;
    generated_at?: string;
    generator?: string;
  }

/** Opaque read-only share token for a project. Token IS the security boundary — treat like a password. */
export interface ShareConfig {
    schema_version: 1;
    project_slug: string;
    token: string;
    created_at: string;
    note?: string;
  }

export type Shot = {
    id: string;
    act: number;
    start_frame: number;
    duration_frames: number;
    /** Must match an id in the catalog / source-catalog for this project. */
    source_id: string;
    /** Source-side in-point (HH:MM:SS.mmm). */
    source_timecode: string;
    role: "hero" | "action" | "reaction" | "environment" | "detail" | "motion" | "gaze" | "cut-on-action" | "establishing" | "transition" | "insert" | "title";
    mood_tags?: Array<string>;
    framing?: "" | "ECU" | "CU" | "MCU" | "medium" | "MS" | "MWS" | "wide" | "WS" | "EWS" | "insert" | "OTS" | "POV";
    /** Screen-space motion direction in degrees (0 = right, 90 = down). Null for static shots. */
    motion_vector?: number | null;
    eyeline?: "" | "left" | "right" | "camera" | "up" | "down" | "mixed";
    /** Which beat/drop/downbeat this shot's start is synced to. */
    beat_sync?: {
    type?: "beat" | "downbeat" | "drop" | "buildup" | "breakdown" | "onset" | "free";
    index?: number;
    time_sec?: number;
  };
    /** Shot-curator T/F/E/B scores (each 0-5). */
    scores?: {
    theme_fit?: number;
    fandom_balance?: number;
    emotion?: number;
    beat_sync_score?: number;
  };
    transition_to_next?: "hard_cut" | "match_cut" | "flash_cut" | "whip_pan" | "dip_to_black" | "cross_dissolve" | "speed_ramp" | "flash_stack" | "morph" | "none";
    safe_area_ok?: boolean;
    cliche_flag?: boolean;
    /** Required when cliche_flag is true — explains why the cliche is intentional. */
    override_reason?: string;
    /** 0 = first use of this source+timecode in the edit. Incremented for each reuse. */
    reuse_index?: number;
    /** Intentional-reuse marker. Absent/null = default, treat as a unique shot and do not pick the same source+timecode twice. */
    intent?: null | "callback" | "motif" | "rhyme";
    /** When intent=callback, the id of the earlier shot this one literally repeats. The proposer will mirror the source_id + source_timecode of the referenced shot. */
    callback_of?: string;
    description?: string;
    color_notes?: string;
    characters?: Array<string>;
    fandom?: string;
    /** Phase 1.3 — taxonomy id from clip-category.schema.json. Drives slot-fit scoring. */
    clip_category?: "establishing" | "action-high" | "action-mid" | "reaction-quiet" | "reaction-emotional" | "dialogue-primary" | "dialogue-reaction" | "transitional" | "climactic" | "resolution" | "texture";
    /** Phase 1.3 — 8-dim emotional vector. Order matches intent.tone_vector: [grief, triumph, fear, awe, tension, release, sorrow, elation]. Each 0-1. */
    emotional_register?: Array<number>;
    /** Phase 1.3 — motion magnitude 0-100, normalized against the source's typical motion baseline. */
    action_intensity_pct?: number;
    /** Phase 1.3 — 0-100 SNR + word-confidence proxy from whisper. Null when no transcript. */
    dialogue_clarity_score?: number | null;
    /** Phase 1.3 — mouth-region motion vs spoken-line plausibility 0-1. Null when no face / no whisper. */
    lip_sync_confidence?: number | null;
    /** Phase 1.3 — inherited from source-profile.source_type so slot-fit can warn on cross-style cuts. */
    visual_style?: "anime" | "live_action" | "western_animation" | "3d_render" | "archival" | "music_video" | "sports" | "documentary" | "mixed";
    /** Phase 1.3 — what kind of audio the source-clip carries. Drives mixer's preserve-diegetic / score-strip / voice-carry decisions. */
    audio_type?: "dialogue_present" | "sfx_only" | "music_clean" | "scene_audio" | "ambience" | "silent";
    /** Phase 1.3 — suitability for [low, mid, high] energy zones, derived from clip_category × clip-categories.energy_zone_affinity. */
    energy_zone_fit?: Array<number>;
    /** Phase 2.2 — composite slot-fit score 0-1 stamped after the slot-fit scorer runs. */
    slot_fit_score?: number;
  };

/** The authoritative shot list for an edit. Produced by shot-curator / ff match shots and consumed by QA gate, NLE exporters, and the dashboard timeline editor. */
export interface ShotList {
    schema_version: 1;
    project_slug: string;
    fps: 23.976 | 24 | 25 | 29.97 | 30 | 48 | 50 | 59.94 | 60;
    resolution: {
    width: number;
    height: number;
  };
    song_duration_sec?: number;
    /** Per-act fandom share targets. QA gate enforces within +/- tolerance. */
    fandom_quota?: Record<string, Record<string, number>>;
    shots: Array<Shot>;
    /** Candidate shots explicitly rejected — kept so the audit trail survives. */
    rejected?: Array<{
    source_id: string;
    source_timecode: string;
    reason: string;
  }>;
    generated_at?: string;
    generator?: string;
  }

export type Source = {
    /** Stable identifier. Prefer the blake3 hash of the raw file; CAS key also fine. */
    id: string;
    path: string;
    fandom: string;
    source_type: "movie" | "tv" | "anime" | "game" | "short" | "trailer" | "other";
    title?: string;
    year?: number;
    media: {
    duration_sec: number;
    width: number;
    height: number;
    fps: number;
    codec: string;
    bitrate_kbps?: number;
    has_audio?: boolean;
    audio_codec?: string;
    audio_channels?: number;
    audio_sample_rate?: number;
    variable_frame_rate?: boolean;
  };
    /** Paths to derived artifacts produced during ingest. */
    derived?: {
    transcript?: string;
    scenes?: string;
    clip_embeddings?: string;
    character_tags?: string;
    stems_dir?: string;
  };
    characters_present?: Array<{
    character: string;
    confidence: number;
    appearances: number;
  }>;
    /** Warnings or blocks attached to this source. */
    flags?: Array<{
    level: "info" | "warn" | "block";
    code: string;
    message: string;
  }>;
    added_at?: string;
  };

/** Per-project source-video catalog. One entry per ingested source with its path, metadata, derived artifacts (transcript, scenes, clip embeddings, character tags). Written by `ff ingest`. */
export interface SourceCatalog {
    schema_version: 1;
    project_slug: string;
    sources: Array<Source>;
    generated_at?: string;
  }

/** Compact fixed-width histogram. bins is always 16 for this schema version. counts is an array of exactly 16 non-negative integers, where counts[i] is the number of sampled pixels falling in the i-th equal-width bin across the 0-255 range of the measured channel. */
export type Histogram16 = {
    /** Number of histogram bins. Fixed at 16 for this schema version. */
    bins: 16;
    /** Raw pixel counts per bin, not normalized. The caller normalizes as needed (e.g. divide by total sampled pixels for a probability mass). Storing raw counts preserves the ability to merge histograms from multiple frames without information loss. */
    counts: Array<number>;
  };

/** Per-source visual and container fingerprint, produced at ingest time. Every field here is computed from the raw video file itself — not from the edit project. This schema is the feeder for Phase 3's visual signature DB, the slot-fit scorer, the aspect-ratio arbiter, the quality-gap mitigator, and the color grader's per-source nudges. A valid record can be produced in a quick-pass (required fields only) without a full feature-extraction run; optional fields fill in as the profiler does deeper analysis. Source-type-neutral by design (A3 constraint): anime, live-action, 3d-render, and archival sources all use the same schema. */
export interface SourceProfile {
    /** Schema version. Always 1 for records conforming to this draft. */
    schema_version: 1;
    /** Foreign key into source-catalog.schema.json. Should be the same stable identifier (blake3 hash or CAS key) used there. */
    source_id: string;
    /** Broad production category of the source. Used by the slot-fit scorer for cross-type blend warnings and by the color grader when choosing a starting LUT strategy. Generic across all edit types — no anime-specific fields; use this tag + era_bucket to represent a 90s anime the same way you'd represent a 2010s live-action film. */
    source_type: "anime" | "live_action" | "western_animation" | "3d_render" | "archival" | "music_video" | "sports" | "documentary";
    /** Production-decade bucket. Drives the color grader's grain-compensation nudge and helps the slot-fit scorer warn when mixing sources from radically different eras (e.g. pre-2000 anime grain next to post-2020 3d render). */
    era_bucket: "pre-2000" | "2000-2010" | "2010-2020" | "post-2020";
    /** Optional free-text era label for human context. Not used by any downstream algorithm — purely for inspection. Example: 'extraction2-2023', 'original-1997-broadcast'. */
    era_label?: string;
    /** Source-level quality tier on the same S/A/B/C/D axis used in reference-priors.schema.json. Applied to the whole source file, not to individual clips. D-tier sources are refused by default unless --allow-dtier is set. */
    quality_tier: "S" | "A" | "B" | "C" | "D";
    /** Known recurring visual defects or editorial constraints detected in this source. Stored as free-text strings so the QA gate and slot-fit scorer can surface them as warnings without needing a fixed enum that would need updating for every new defect type. Examples: 'HUD overlay', 'watermark', 'consistent dark scenes', 'heavy compression', 'interlace artifacts', 'timecode burn-in'. */
    visual_hazards?: Array<string>;
    /** 16-bin luminance histogram averaged across sampled frames. Bins span 0-255 in equal steps (each bin covers 16 luma units). Stored as integer counts (not normalized) so the caller controls normalization. 16 bins chosen over 32 to keep per-source records compact while retaining enough discriminatory power for luma-range matching (e.g. detecting consistently dark sources vs. blown-out sources). */
    luma_histogram?: Histogram16;
    /** 16-bin chroma saturation histogram averaged across sampled frames. Bins span 0-255 chroma magnitude in equal steps. Useful for distinguishing heavily desaturated sources (grief-tone tribute) from oversaturated sources (hyper-stylized anime). Same 16-bin rationale as luma_histogram. */
    chroma_histogram?: Histogram16;
    /** Estimated dominant color temperature in Kelvin, derived from the white-balance of sampled frames. Not a camera-sensor reading — this is a perceptual estimate used to flag warm/cool source mismatches going into the color grader. */
    color_temperature_kelvin?: {
    /** Estimated color temperature in Kelvin. Typical range: 2700K (tungsten warm) to 6500K (daylight) to 9000K+ (blue-shifted archival or stylized anime). */
    estimate_k: number;
    /** Profiler confidence in the estimate. Low confidence expected for heavily color-graded sources or sources with strongly mixed lighting. */
    confidence: number;
  };
    /** Mean saturation of sampled frames, normalized 0-1. Quick scalar proxy for the chroma_histogram. 0 = fully desaturated / black-and-white, 1 = maximally saturated. */
    saturation_avg?: number;
    /** Dominant color cast across sampled frames. Used by the color grader when computing the nudge needed to blend this source into a unified palette. */
    color_cast?: {
    /** Dominant hue angle in degrees (0=red, 60=yellow, 120=green, 180=cyan, 240=blue, 300=magenta). */
    hue_degrees: number;
    /** Up to 5 dominant hex colors sampled via k-means across profiled frames. Stored as 6-digit uppercase hex strings without the # prefix. */
    dominant_colors?: Array<string>;
  };
    /** Proxy measure of film grain or compression noise, 0-1. Computed as the median high-pass energy across sampled frames after a sharpening kernel is subtracted. 0 = clean digital, 1 = heavy grain or severe compression noise. Used by the quality-gap mitigator to flag sources that will look mismatched next to clean digital sources. */
    grain_noise_floor?: number;
    /** Edge density proxy for perceived sharpness, 0-1. Computed as the normalized mean of a Laplacian edge map across sampled frames. 0 = soft / heavily blurred, 1 = very sharp. Distinct from grain_noise_floor: high sharpness + high grain = over-sharpened noisy source. Low sharpness + low grain = intentional soft look (some 2000s anime). */
    sharpness_score?: number;
    /** Native display aspect ratio of the source file expressed as a ratio string. Must capture the actual display ratio, not the pixel storage ratio. Examples: '16:9', '4:3', '2.39:1', '1:1', '9:16'. Letterboxed or pillarboxed sources should report the enclosing container ratio here and set letterbox_detected or pillarbox_detected true. */
    aspect_ratio_native: string;
    /** Native playback frame rate of the source in frames per second. Use the exact container value (e.g. 23.976, 29.97, 24.0, 60.0). Used by the aspect-ratio arbiter when checking for frame-rate mismatch risk at the timeline join point. */
    framerate_native: number;
    /** Native pixel resolution of the source container. */
    resolution_native: {
    /** Frame width in pixels. */
    width: number;
    /** Frame height in pixels. */
    height: number;
  };
    /** True if horizontal black bars were detected at the top and bottom of sampled frames, indicating the active picture is narrower vertically than the container. Triggers a crop-or-pad decision in the aspect-ratio arbiter. */
    letterbox_detected: boolean;
    /** True if vertical black bars were detected on the left and right sides of sampled frames, indicating the active picture is narrower horizontally than the container (common in 4:3 content in a 16:9 wrapper). */
    pillarbox_detected: boolean;
    /** Number of frames that were analyzed to compute the visual stats in this profile. The visual stat fields (luma_histogram, chroma_histogram, grain_noise_floor, sharpness_score, saturation_avg, color_cast, color_temperature_kelvin) are only as reliable as this count. A quick-pass profiler might sample 30 frames; a deep-pass profiler might sample 500+. */
    frames_sampled: number;
    /** ISO 8601 date-time when this profile was generated. */
    generated_at: string;
    /** Name and version of the profiler that produced this record. Examples: 'source_profiler/0.1.0', 'source_profiler/0.2.0+manual'. Bumping the profiler version and re-ingesting will produce a new profile; comparing generator values is how you detect stale profiles. */
    generator: string;
  }

/** Unifies the song's structural points (drops, breakdowns, buildups, downbeats) with timestamped lyric sections, and recommends which shots from the shot list should land on each point. Produced by `ff sync plan` and consumed by the timeline editor + NLE export to surface sync opportunities. */
export interface SyncPlan {
    schema_version: 1;
    project_slug: string;
    song_title?: string;
    /** Timestamped lyric sections derived from whisper on the song audio. */
    lyrics?: Array<{
    start_sec: number;
    end_sec: number;
    text: string;
    emotion?: "intense" | "somber" | "hopeful" | "defiant" | "tender" | "neutral";
    confidence?: number;
  }>;
    /** Every significant moment on the song timeline with recommended shots. */
    song_points: Array<{
    id: string;
    time_sec: number;
    end_sec?: number;
    type: "lyric" | "drop" | "buildup" | "breakdown" | "downbeat" | "custom";
    label: string;
    emotion?: "intense" | "somber" | "hopeful" | "defiant" | "tender" | "neutral";
    intensity?: number;
    /** Ordered list of shot ids (from shot-list.json) that best match this point. First is the top recommendation. */
    recommended_shots?: Array<{
    shot_id: string;
    score: number;
    reasons?: Array<string>;
  }>;
  }>;
    generated_at?: string;
    generator?: string;
  }

/** Per-second tension model derived from beat-map energy + emotion-arc + arc-architect's tension_target per act. Each sample carries the target tension and the actual tension the rendered shot list contributes. Phase 4's arc_shape evaluator scores the gap. Cross-type by design: action and emotional both use the same -1..+1 scale, only the target curves differ. */
export interface TensionCurve {
    schema_version: 1;
    duration_sec: number;
    /** Sample interval. 1.0s default. */
    resolution_sec?: number;
    /** Sequential per-resolution_sec samples covering 0..duration_sec. */
    samples: Array<{
    time_sec: number;
    target_tension: number;
    actual_tension: number;
    /** actual - target. */
    delta?: number;
    act_index?: number;
    arc_role?: "setup" | "escalation" | "climax" | "release" | "interlude";
  }>;
    /** Aggregate stats useful for QA + review. */
    summary?: {
    peak_target?: number;
    peak_actual?: number;
    peak_actual_time_sec?: number;
    /** Root-mean-square of (actual - target) across all samples. 0 = perfect match. */
    rms_delta?: number;
    /** True if actual tension monotonically trends up into the climax act. */
    builds_to_climax?: boolean;
    /** True if actual tension drops or peaks-and-holds in the release act. */
    resolves?: boolean;
  };
    generated_at?: string;
    generator?: string;
  }

export type Title = {
    id: string;
    text: string;
    in_frame: number;
    out_frame: number;
    font: string;
    font_weight?: "thin" | "light" | "regular" | "medium" | "semibold" | "bold" | "heavy" | "black";
    italic?: boolean;
    size_px: number;
    color?: string;
    stroke_color?: string;
    stroke_width_px?: number;
    background?: {
    color?: string;
    opacity?: number;
    padding_px?: number;
  };
    position: {
    x: number;
    y: number;
    anchor: "top-left" | "top-center" | "top-right" | "center-left" | "center" | "center-right" | "bottom-left" | "bottom-center" | "bottom-right";
  };
    animation?: {
    in_preset?: "none" | "fade" | "slide_up" | "slide_down" | "slide_left" | "slide_right" | "type_on" | "zoom_in" | "kinetic_stack";
    out_preset?: "none" | "fade" | "slide_up" | "slide_down" | "slide_left" | "slide_right" | "type_off" | "zoom_out";
    in_frames?: number;
    out_frames?: number;
  };
    safe_area_ok: boolean;
    /** Which platform's safe area was checked. */
    platform_safe_area?: "youtube" | "tiktok" | "reels" | "shorts" | "twitter" | "master";
  };

/** Per-project title/overlay plan. Produced by title-designer, consumed by QA gate (safe-area check) and NLE exporters (as essential-graphics / Fusion titles). */
export interface TitlePlan {
    schema_version: 1;
    project_slug: string;
    fps: number;
    resolution: {
    width: number;
    height: number;
  };
    titles: Array<Title>;
    generated_at?: string;
    generator?: string;
  }

/** Word-level transcript produced by Whisper or parsed from SRT. One file per source. */
export interface Transcript {
    schema_version: 1;
    source_id: string;
    /** ISO 639-1 code. */
    language: string;
    /** Which transcription model produced this. e.g. 'whisper-large-v3', 'srt-import', 'openai-api'. */
    model?: string;
    segments: Array<{
    id?: number;
    start_sec: number;
    end_sec: number;
    text: string;
    character?: string;
    confidence?: number;
    words?: Array<{
    word: string;
    start_sec: number;
    end_sec: number;
    confidence?: number;
  }>;
  }>;
    generated_at?: string;
  }

export type Transition = unknown & unknown;

/** Frame-accurate per-cut transition plan. Produced by transition-architect / ff match transitions and consumed by NLE exporters. */
export interface TransitionPlan {
    schema_version: 1;
    project_slug: string;
    fps: number;
    transitions: Array<Transition>;
    generated_at?: string;
    generator?: string;
  }

export type Endpoint = {
    id: string;
    url: string;
    /** Shared secret used for HMAC signature. Store securely. */
    secret?: string;
    events: Array<"pipeline.started" | "pipeline.completed" | "pipeline.failed" | "qa.gate.passed" | "qa.gate.failed" | "artifact.applied" | "export.ready" | "autopilot.step.failed" | "autopilot.completed">;
    enabled?: boolean;
    created_at?: string;
    description?: string;
  };

/** Per-project webhook config. Fires signed POST requests on pipeline events. */
export interface Webhooks {
    schema_version: 1;
    project_slug: string;
    endpoints: Array<Endpoint>;
  }

export interface ArtifactSchemaMap {
  "audio-plan": AudioPlan;
  "beat-map": BeatMap;
  "catalog": Catalog;
  "clip-category": ClipCategory;
  "color-plan": ColorPlan;
  "complement-plan": ComplementPlan;
  "dialogue-placement-plan": DialoguePlacementPlan;
  "dialogue-windows": DialogueWindows;
  "edit-plan": EditPlan;
  "emotion-arc": EmotionArc;
  "energy-zones": EnergyZones;
  "fandoms": Fandoms;
  "intent": Intent;
  "post-render-review": PostRenderReview;
  "project-config": ProjectConfig;
  "psychology-report": PsychologyReport;
  "qa-report": QaReport;
  "reference-priors": ReferencePriors;
  "scenes": Scenes;
  "sfx-plan": SfxPlan;
  "share-config": ShareConfig;
  "shot-list": ShotList;
  "source-catalog": SourceCatalog;
  "source-profile": SourceProfile;
  "sync-plan": SyncPlan;
  "tension-curve": TensionCurve;
  "title-plan": TitlePlan;
  "transcript": Transcript;
  "transition-plan": TransitionPlan;
  "webhooks": Webhooks;
}

export type ArtifactSchemaId = keyof ArtifactSchemaMap;

export const ARTIFACT_SCHEMA_IDS: readonly ArtifactSchemaId[] = ["audio-plan", "beat-map", "catalog", "clip-category", "color-plan", "complement-plan", "dialogue-placement-plan", "dialogue-windows", "edit-plan", "emotion-arc", "energy-zones", "fandoms", "intent", "post-render-review", "project-config", "psychology-report", "qa-report", "reference-priors", "scenes", "sfx-plan", "share-config", "shot-list", "source-catalog", "source-profile", "sync-plan", "tension-curve", "title-plan", "transcript", "transition-plan", "webhooks"] as const;
